### ISSUE TITLE
Getting failure when running this script

### ISSUE THREAD

**Issue by saurabh622** [sgsvenkatesh/cisco-vpn-auto-login#1]
I followed the steps and set the password in the file and exported it as application

but i get this error.
cisco-vpn-auto-login is not allowed to send keystrokes.

**Comment by sgsvnk** [comment]
See instructions here - https://apple.stackexchange.com/a/466484

**Comment by saurabh622** [comment]
This is not working for me, i tried following these steps, I am using M1 MacOs
